08-Social-Blog-Project/Final_Project/puppycompanyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('BlogPost')

08-Social-Blog-Project/Final_Project/puppycompanyblog/blog_posts/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from puppycompanyblog import db
from puppycompanyblog.models import BlogPost
from puppycompanyblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id
                             )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


# int: makes sure that the blog_post_id gets passed as in integer
# instead of a string so we can look it up later.
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    # grab the requested blog post by id number or return 404
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post
    )

@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Update',
                           form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

08-Social-Blog-Project/Final_Project/puppycompanyblog/core/views.py
from flask import render_template,request,Blueprint
from puppycompanyblog.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)
    return render_template('index.html',blog_posts=blog_posts)

@core.route('/info')
def info():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('info.html')

08-Social-Blog-Project/Final_Project/puppycompanyblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from puppycompanyblog import db
from werkzeug.security import generate_password_hash,check_password_hash
from puppycompanyblog.models import User, BlogPost
from puppycompanyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from puppycompanyblog.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        # Check that the user was supplied and the password is right
        # The verify_password method comes from the User object
        # https://stackoverflow.com/questions/2209755/python-operation-vs-is-not

        if user.check_password(form.password.data) and user is not None:
            #Log in the user

            login_user(user)
            flash('Logged in successfully.')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

08-Social-Blog-Project/Final_Project/puppycompanyblog/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>

</div>

{% endblock content %}

08-Social-Blog-Project/Final_Project/puppycompanyblog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <ul class="nav">

  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('core.info') }}">About Us</a>
  </li>
    {% if current_user.is_authenticated %}
    <li class="nav-link"><a href="{{ url_for('users.logout') }}">Log Out</a></li>
    <li class="nav-link"><a href="{{ url_for('users.account') }}">Account</a></li>
    <li class="nav-link"><a href="{{ url_for('blog_posts.create_post') }}">Create Post</a></li>
    {% else %}
    <li class="nav-link"><a href="{{ url_for('users.login') }}">Log In</a></li>
    <li class="nav-link"><a href="{{ url_for('users.register') }}">Register</a></li>
    {% endif %}

</ul>
<div class="container">
  {% block content %}

  {% endblock %}
</div>


  </body>
</html>

08-Social-Blog-Project/Final_Project/puppycompanyblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

08-Social-Blog-Project/Final_Project/puppycompanyblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>

{% endblock content %}

08-Social-Blog-Project/Final_Project/puppycompanyblog/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Puppy Company Blog</h1>
    <p>Welcome to Our Company's Blog Page</p>
  </div>

  <div class="container">

    {# Go through each blog post #}
    {% for post in blog_posts.items %}

    <div class="card" >

      <div class="card-body">


        <h2><a class="card-title" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
      </div>
    </div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>




{% endblock %}

08-Social-Blog-Project/Final_Project/puppycompanyblog/templates/info.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Info about our Company</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

{% endblock %}

08-Social-Blog-Project/Final_Project/puppycompanyblog/templates/login.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}
    {{ form.password.label }} {{ form.password() }}
    {{ form.submit() }}
</form>
{% endblock %}

08-Social-Blog-Project/Final_Project/puppycompanyblog/templates/register.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}<br>
    {{ form.username.label }} {{ form.username() }}<br>
    {{ form.password.label }} {{ form.password() }}<br>
    {{ form.pass_confirm.label }} {{ form.pass_confirm() }}<br>
    {{ form.submit() }}
</form>
{% endblock %}

08-Social-Blog-Project/Final_Project/puppycompanyblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for post in blog_posts.items %}

          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}